# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    dupl:
      threshold: 100
    govet:
      shadow:
        strict: true

output:
  formats: 
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true



