# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

output:
  formats: 
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true



